### ISSUE TITLE
Tool returned our moderation comment counts to be wrong

### ISSUE THREAD

**Issue by rigperro** [coralproject/coral-counts#25]
We migrated some older comments from Coral Talk v4 to v6. These comments were then moderated in the newer version and our moderation counts were left negative. I fixed this by connecting to Redis and incrementing the counts by hand. We could be facing a similar issue later on as well, and I asked via email if there is a safe way to do this in the future. Support responded me with a link to this repository. I tried it and it returned the comment counts to negative, negating the manual fix I had made. Am I using this wrong?
![image](https://user-images.githubusercontent.com/34183521/144439849-7c68051d-3dd4-4d78-a327-4b7a4ef76f6c.png)

**Comment by immber** [comment]
Making manual changes to redis before running this tool is why it did not work. You would need to revert your manual changes in redis, or just delete any redis keys related to `keys *commentCounts*` before running the count fix tool. 

When this tool runs, it updates mod queue counts based on the `commentCounts` object on `site` documents in mongo.
